#ifndef ELIYIR_MOWER_CONFIG_H
#define ELIYIR_MOWER_CONFIG_H
#include <driver/dac.h>

//PIN DEFINITION
#define PIN_LEFT_MOTOR_VR DAC_CHANNEL_1   // GPIO25 - DAC channel 1 
#define PIN_RIGHT_MOTOR_VR DAC_CHANNEL_2    //GPIO26 - DAC channel 2
#define PIN_LEFT_MOTOR_EL 32    
#define PIN_RIGHT_MOTOR_EL 33  
#define PIN_LEFT_MOTOR_DIR 27    
#define PIN_RIGHT_MOTOR_DIR 14  
#define PIN_LEFT_MOTOR_SPEED_SENSE 34  
#define PIN_RIGHT_MOTOR_SPEED_SENSE 35  

#define PIN_LEFT_PERIMETER_SENSE 36  
#define PIN_RIGHT_PERIMETER_SENSE 39  

#define PARAM_MOTOR_SPEED_MAX_PWM 180  
#define PARAM_MOTOR_SPEED_MIN_PWM 10  


#endif // ELIYIR_MOWER_CONFIG_H